name = "replate-donor-spa"
compatibility_date = "2025-09-03"
preview_urls = false

routes = [
    { pattern = "donor.replate.dev/*", zone_name = "replate.dev" },
    { pattern = "donor.replate.uk/*", zone_name = "replate.uk" }
]

[build]
command = "npm run build"
#command = "npm run build:ts"

[assets]
directory = "./public"
not_found_handling = "single-page-application"

